### ISSUE TITLE
doc: list the actions available on the main README

### ISSUE THREAD

**Issue by educhastenier** [bonitasoft/actions#109]
For someone who is not aware of the actions Bonitasoft provides, it is hard to know what they will find here.
Just listing https://github.com/bonitasoft/actions/tree/main/packages is not enough.

**Comment by tbouffard** [comment]
Hi,
I guess what you suggest is to list all actions available in the packages directory and provide a short description for each available action.
We can do this but I cannot guarantee the list will be always up-to-date. This is probably why we put a link to the packages root directory. I suggest that we keep this link so that we can have the complete list.

**Comment by educhastenier** [comment]
> Hi, I guess what you suggest is to list all actions available in the packages directory and provide a short description for each available action. We can do this but I cannot guarantee the list will be always up-to-date. This is probably why we put a link to the packages root directory. I suggest that we keep this link so that we can have the complete list.

Yes, this is what I suggest. Ok to keep the link to make sure we don't miss anything.
My idea is just to ease understanding what is the list of actions available.
